// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcYk-_wFxJ_RjAdq6IzFKULcJ2dGrwATA',
    appId: '1:421788068038:web:096b590f7090b36125cfc7',
    messagingSenderId: '421788068038',
    projectId: 'e-commerce-24a66',
    authDomain: 'e-commerce-24a66.firebaseapp.com',
    storageBucket: 'e-commerce-24a66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ82dAFntpzgwS6fliBPjvwwBE7iTpRhM',
    appId: '1:421788068038:android:5c219ae155ca0a6925cfc7',
    messagingSenderId: '421788068038',
    projectId: 'e-commerce-24a66',
    storageBucket: 'e-commerce-24a66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2-kzjJDLVJaZjYXLPhUmF2z6dSuhjcxo',
    appId: '1:421788068038:ios:1d0a20a0e31a787925cfc7',
    messagingSenderId: '421788068038',
    projectId: 'e-commerce-24a66',
    storageBucket: 'e-commerce-24a66.appspot.com',
    androidClientId: '421788068038-95079m8shngsojkb3mpsd9uj6co3jab8.apps.googleusercontent.com',
    iosClientId: '421788068038-jspooa2ej8mjlas6e85b0d3r423dbfn8.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}